name: Deploy
on:
  push:
    branches: [main]

jobs:
  tests:
  	runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup and Run Tests
        run:  |
          docker-compose build
          docker-compose run web rake db:setup
          docker-compose run web rspec
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow succeeded deploying now'
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          usedocker: true
